on:
   schedule:
    - cron:  '* * * * *'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: actions/hello-world-docker-action@v1
      with:
        who-to-greet: 'Parsa'
    # Use the output from the `hello` step
    - name: Get the output time
      id: step2
      run: echo "The time was ${{ steps.hello.outputs.time }}"
    - name: Write my name
      id: step3
      run: echo "Hello $GITHUB_ACTOR !"
         
    
    - name: clone with secret
      id: step5
      run: |
           pwd
           ls -la
           git clone https://parsalotfy:${{ secrets.GITHUB_TOKEN }}@github.com/parsalotfy/ActionTest.git
           pwd
           ls -la
    
    - name: Change Directory
      id: step6
      run: |
           ls -la
           cd ActionTest/
           pwd
           ls -la
      
    - name: Set Email
      id: step7
      run: |
           pwd 
           ls -la
           git config user.email parsalotfy@outlook.com
           pwd
           ls -la
         
    - name: Write to file
      id: step8
      run: echo $(date) >> README.md     
     
    - name: Commit changes 
      id: step9
      run: git commit -am $(date)
     
    - name: Push
      id: step10
      run: git push
    
         
      
      
         
       
