on:
   schedule:
    - cron:  '* * * * *'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: actions/hello-world-docker-action@v1
      with:
        who-to-greet: 'Parsa'
    # Use the output from the `hello` step
    - name: Get the output time
      id: step2
      run: echo "The time was ${{ steps.hello.outputs.time }}"
    - name: Write my name
      id: step3
      run: echo "Hello $GITHUB_ACTOR !"
    - name: Update and Upgrage
      id: step4
      run: |
         apk update
         apk upgrade
         
    -name: Install git
     id: step5
     run: apk add --no-cache git
     
    -name: clone with secret
     id: step6
     run: git clone https://parsalotfy:${{ secrets.GITHUB_TOKEN }}@github.com/parsalotfy/ActionTest.git
    
    -name: Change Directory
     id: step7
     run: cd ActionTest/
      
    -name: Set Email
     id: step8
     run: git config user.email parsalotfy@outlook.com
         
    -name: Write to file
     id: step9
     run: echo $(date) >> README.md     
     
    -name: Commit changes 
     id: step10
     run: git commit -am $(date)
     
    -name: Push
     id: step11
     run: git push
    
         
      
      
         
       
