on:
   schedule:
    - cron:  '* * * * *'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
              
    - name: Hello world action step
      id: hello
      uses: actions/hello-world-docker-action@v1
      with:
        who-to-greet: 'Parsa'
             
         
  
    # Use the output from the `hello` step
    - name: Get the output time
      id: step2
      run: echo "The time was ${{ steps.hello.outputs.time }}"
      
      
    - name: Write my name
      id: step3
      run: echo "Hello $GITHUB_ACTOR !"
         
    
    - name: clone with secret
      id: step4
      run: git clone https://parsalotfy:${{ secrets.GITHUB_TOKEN }}@github.com/parsalotfy/ActionTest.git          
    
    - name: Create file
      id: step5
      run: touch 1.txt
      
    - name: see file
      id: step6
      run: ls -la   
      
    - name: docker test
      id: step7
      run: docker ps  
        
